### ISSUE TITLE
选择器都出不来

### ISSUE THREAD

**Issue by a728384698** [mqy1023/rn-wheel-picker-china-region#2]
1.npm 了也link 了。
2.import ChinaRegionWheelPicker from 'rn-wheel-picker-china-region';
3.   －－－－iOS 方法一－－－－－                
 <ChinaRegionWheelPicker
                        onSubmit={(params) => this.setState({ region1:`${params.province},${params.city},${params.area}`})}
                        onCancel={() => console.log('cancel')}
                    >
                    </ChinaRegionWheelPicker>

放到了我的点击事件下面，但是选择器都没有出来 。请问什么原因！

**Comment by mqy1023** [comment]
你可以参考ios用法一，是显示文本放进ChinaRegionWheelPicker里面，点击事件你不用处理
// ios用法一
<ChinaRegionWheelPicker
  onSubmit={(params) => this.setState({ region1: `${params.province},${params.city},${params.area}` })}
  onCancel={() => console.log('cancel')}
>
  <TextInput
    editable={false}
    placeholder="点击去选择地区"
    value={this.state.region1}
  />
</ChinaRegionWheelPicker>
